### ISSUE TITLE
Накрутка денег

### ISSUE THREAD

**Issue by sashabondar41** [xtrdnrmnd/Course_project_OOP#8]
При попытке выдать количество денег большее, чем есть на счету, можно получить прибавление баланса. Причем сумма пополнения никак не связана с суммой снятия.
![image](https://user-images.githubusercontent.com/75033340/154751752-982c850d-f3ff-4316-be98-ccbb4570a262.png)
![image](https://user-images.githubusercontent.com/75033340/154751784-4ea8605a-9333-4cd9-90fa-a0dff469a4f9.png)
![image](https://user-images.githubusercontent.com/75033340/154751802-0a2e58ac-a120-4cd7-ac0c-c7aaec5b3c91.png)
![image](https://user-images.githubusercontent.com/75033340/154751833-c48c7366-e803-43d5-8b5e-5a32f7e6d6b3.png)

**Comment by xtrdnrmnd** [comment]
Данный баг уже был описан ранее. Наша команда осведомлена и работает над решением.
